// Run with playwright-cli run-code --filename after signing in to a synthetic
// local test account. The harness must route all /api/** to the local test API.
async (page) => {
  await page.setViewportSize({ width: 1257, height: 934 })
  await page.waitForLoadState('networkidle')
  await page.getByRole('button', { name: 'Приоритеты', exact: true }).click()
  const check = (condition, message) => { if (!condition) throw Error(message) }
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  const task = 'Задача для проверки разделения'
  const title = 'Выпустить новый продукт'
  const renamed = 'Выпустить Tommma для команды'
  const section = () => page.getByRole('region', { name: 'Приоритеты: Цели', exact: true })
  const selectGoals = () => page.getByRole('button', { name: 'Цели', exact: true }).click()
  check(await page.getByRole('button', { name: 'Задачи', exact: true }).getAttribute('aria-pressed') === 'true', 'Tasks open by default')
  if (await page.getByRole('button', { name: `Редактировать задачу: ${task}`, exact: true }).count() === 0) {
    const taskInput = page.getByRole('textbox', { name: 'Добавить задачу во Входящие', exact: true })
    await taskInput.fill(task)
    await taskInput.press('Enter')
    await page.getByRole('button', { name: `Редактировать задачу: ${task}`, exact: true }).waitFor()
  }
  await selectGoals()
  const add = section().getByRole('textbox', { name: 'Добавить цель во Входящие', exact: true })
  await add.waitFor()
  check(await section().locator('.priority-task').count() === 0, 'Goals start independently empty')
  await add.fill(title)
  await add.press('Enter')
  const edit = () => section().getByRole('button', { name: `Редактировать цель: ${title}`, exact: true })
  await edit().waitFor()
  const row = section().locator('.priority-task').filter({ has: page.getByRole('button', { name: `Редактировать цель: ${title}`, exact: true }) })
  check(await row.locator('.task-lives,.task-elapsed,[id^="priority-subtasks-"],.priority-subtasks-toggle').count() === 0, 'Goals have no lives, timers or subtasks')
  check(await section().getByRole('checkbox').count() === 0, 'Goals have no checkboxes')
  check(await row.locator('.goal-priority-stepper').count() === 1, 'Goals have one priority counter')
  check(await row.locator('.task-score,.task-weight').count() === 0, 'Retired scores and weight are absent')
  check(await section().getByRole('button', { name: `Уменьшить приоритет: ${title}`, exact: true }).isDisabled(), 'Zero is the minimum priority')
  for (let i = 0; i < 12; i++) await section().getByRole('button', { name: `Увеличить приоритет: ${title}`, exact: true }).click()
  await section().getByLabel('Приоритет цели: 12', { exact: true }).waitFor()
  await edit().click()
  const input = section().getByRole('textbox', { name: `Название цели: ${title}`, exact: true })
  check(await input.evaluate(el => el.selectionStart === el.selectionEnd), 'Inline edit must not auto-select existing text')
  await input.fill(renamed)
  await input.press('Enter')
  await section().getByRole('button', { name: `Редактировать цель: ${renamed}`, exact: true }).waitFor()
  await page.getByRole('button', { name: 'Задачи', exact: true }).click()
  await page.getByRole('button', { name: `Редактировать задачу: ${task}`, exact: true }).waitFor()
  check(await page.locator('.task-lives').count() > 0, 'Tasks retain timers and lives')
  check(await page.getByText(renamed, { exact: true }).count() === 0, 'Goals never enter tasks')
  await page.reload()
  await page.waitForLoadState('networkidle')
  await page.getByRole('button', { name: 'Приоритеты', exact: true }).click()
  await selectGoals()
  await section().getByRole('button', { name: `Редактировать цель: ${renamed}`, exact: true }).waitFor()
  await section().getByLabel('Приоритет цели: 12', { exact: true }).waitFor()
  check(await section().getByRole('checkbox').count() === 0, 'Ranked goals have no checkboxes')
  // Seed an existing completed goal through the isolated local API, since the UI has no completion checkbox.
  await page.evaluate(async title => {
    const snapshot = await fetch('/api/goals').then(response => response.json())
    const goal = snapshot.goals.find(row => row.title === title)
    const response = await fetch(`/api/goals/${goal.id}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ completed: true, baseUpdatedAt: goal.updatedAt }) })
    if (!response.ok) throw Error('Could not seed completed goal')
  }, renamed)
  await page.reload()
  await page.waitForLoadState('networkidle')
  await page.getByRole('button', { name: 'Приоритеты', exact: true }).click()
  await selectGoals()
  await section().getByRole('button', { name: 'Выполненные 1 цель', exact: true }).waitFor()
  await section().getByRole('button', { name: 'Статистика', exact: true }).click()
  const statistics = page.getByRole('region', { name: 'Статистика целей', exact: true })
  await statistics.getByText(renamed, { exact: true }).waitFor()
  check(await statistics.locator('.task-lives,.task-elapsed').count() === 0, 'Goal statistics exclude time and lives')
  await statistics.getByRole('button', { name: '30 дней', exact: true }).click()
  await statistics.getByRole('button', { name: '90 дней', exact: true }).click()
  await statistics.getByRole('button', { name: 'К целям', exact: true }).click()
  await section().getByRole('button', { name: 'Выполненные 1 цель', exact: true }).click()
  check(await section().getByRole('checkbox').count() === 0, 'Completed goals have no checkboxes')
  await section().getByRole('button', { name: `Вернуть цель во Входящие: ${renamed}`, exact: true }).click()
  await section().getByText('Здесь пока пусто', { exact: true }).waitFor()
  await section().getByRole('button', { name: 'Приоритеты', exact: true }).click()
  await section().getByRole('button', { name: `Редактировать цель: ${renamed}`, exact: true }).waitFor()
  await section().locator('.inbox-group .priority-task').hover()
  await section().getByRole('button', { name: `Удалить цель: ${renamed}`, exact: true }).click()
  await section().getByRole('button', { name: 'Корзина 1 цель', exact: true }).click()
  await section().getByRole('button', { name: `Восстановить цель: ${renamed}`, exact: true }).click()
  await section().getByText('Корзина пуста', { exact: true }).waitFor()
  await section().getByRole('button', { name: 'Приоритеты', exact: true }).click()
  await section().getByRole('button', { name: `Редактировать цель: ${renamed}`, exact: true }).waitFor()
  // A failed save rolls back scores and preserves the retryable input.
  const failScore = route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Проверка сбоя сохранения' }) })
  await page.route('**/api/goals/*/priority-score', failScore)
  await section().getByRole('button', { name: `Увеличить приоритет: ${renamed}`, exact: true }).click()
  await section().getByRole('alert').waitFor()
  await section().getByLabel('Приоритет цели: 12', { exact: true }).waitFor()
  await page.unroute('**/api/goals/*/priority-score', failScore)
  await section().getByRole('button', { name: 'Повторить', exact: true }).click()
  await section().getByRole('alert').waitFor({ state: 'hidden' })
  await section().getByRole('button', { name: `Увеличить приоритет: ${renamed}`, exact: true }).click()
  await section().getByLabel('Приоритет цели: 13', { exact: true }).waitFor()
  await section().getByRole('heading', { name: 'Приоритеты', exact: true }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'output/playwright/goals-desktop.png' })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.waitForFunction(() => document.querySelector('.app-sidebar').getBoundingClientRect().right <= 0)
  await section().getByRole('heading', { name: 'Приоритеты', exact: true }).scrollIntoViewIfNeeded()
  check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile page must not overflow horizontally')
  check(await section().getByRole('button', { name: 'Задачи', exact: true }).isVisible(), 'Mobile tasks switch remains visible')
  check(await section().getByRole('button', { name: 'Цели', exact: true }).isVisible(), 'Mobile goals switch remains visible')
  await page.screenshot({ path: 'output/playwright/goals-mobile.png' })
  await section().getByRole('button', { name: 'Статистика', exact: true }).click()
  await page.screenshot({ path: 'output/playwright/goals-statistics-mobile.png' })
  check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile statistics must not overflow horizontally')
  check(errors.length === 0, `Unexpected browser errors: ${errors.join('; ')}`)
  console.log('PASS goals: one unlimited counter, no checkboxes, empty state, create, scoring, inline edit selection, task isolation, reload persistence, completion, statistics, reopen, delete, restore, failure/retry, desktop 1257x934, mobile 390x844')
}
