ALTER TABLE "tasks"
  ADD COLUMN "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "daily_earnings"
  ADD COLUMN "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "notes_states"
  ADD COLUMN "deleted_note_ids" JSONB NOT NULL DEFAULT '{}'::jsonb;
